# vim:ff=unix:ts=2:sw=2:ai:expandtab
---
version: '3.5'
services:
  cgit:
    build:
      context: .
      cache_from:
        - adarnimrod/cgit
    image: adarnimrod/cgit
    ports:
      - 80:80
    volumes:
      - git:/srv/git:ro

volumes:
  git:
    labels:
      snapshot: 'true'

networks:
  default:
    name: shore
